### ISSUE TITLE
[Question] Double Metaphone Max Length of 4

### ISSUE THREAD

**Issue by jpatel531** [antzucaro/matchr#8]
Hi there! I was wondering why there is a hardcoded max length of 4 for double metaphone? (I've also noticed other implementations limit this to 4). Is there a particular design decision behind this?

**Comment by antzucaro** [comment]
Hey @jpatel531, I think this is primarily because phonetic algorithms are concerned with shrinking the search space as much as possible. They are used as indexes! As a matter of fact, one of the first ones (Soundex, in [this patent][patent]) directly mentions both book and card-based indexing uses.

In other words, they are trying to decrease the number of bytes (length of the encoding) by as much as possible while still retaining the ability to tell the difference between strings that are pronounced differently. The more runes included in the encoding values, the further away you get from that goal.

I hope that helps! Cheers.

[patent]: https://patents.google.com/patent/US1435663

**Comment by antzucaro** [comment]
I'd really recommend against changing that. Phonetic encodings shouldn't be the end-all, be-all in record linkage (entity resolution) scenarios, but rather a piece of a larger whole. If the encoding is bringing too many names together, consider adding an additional rule to the process to guard against it. Some examples using Soundex as the algorithm:

* The input name length must be greater than a certain length for the Soundex code to be considered.
* Add two Soundex codes together: one using the first part of the name, another using the last part of the name by reversing the name string first, thus giving you "signal" from the front part and the last part of the name.
* The input names must be within a certain Levenshtein distance and their Soundex codes in agreement before proceeding.

Etc etc. 

Soundex, Phonex, Phonix, NYSIIS, and the Metaphone variants **all** have a limited length (usually 4, but sometimes 3). Those were determined by people with a ton more experience and expertise than myself, so I think it is probably a better idea to incorporate additional steps in your entity resolution process to guard against  false positives. After all, there are a lot of names out there that share leading phonetic sounds, thus  robbing you of _some_ signal in their encoding!

A great resource for entity resolution and name matching is [this study][study] (especially the bibliography). In general Peter Christen is an amazing researcher, and I can't recommend his "Data Matching: Concepts and Techniques" book enough. It is sitting on my side table right now, years after I left the work job where I did record linkage every day!

[study]: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.65.7311&rep=rep1&type=pdf

**Comment by jpatel531** [comment]
Thank you so much for the resources, and for generally being so helpful. I'll definitely take your advice on board :)
